### ISSUE TITLE
Swift 3 and SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [Ekhoo/Translucid#4]
Hi,
It's will be great to create a [Swift 3](https://swift.org/blog/swift-3-0-release-process/) version of your component 

Article about **Swift 3**: 
- [Migrating to Swift 2.3 or Swift 3 from Swift 2.2](https://swift.org/migration-guide/)

With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
- [Package.swift — The Manifest File](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md)
- [Developing Packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/DevelopingPackages.md)
- [System Modules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md)
- [Swift Package Manager Community Proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md)

On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by armcast** [comment]
Forked version that works on Swift 4.2
https://github.com/armcast/Translucid

**Comment by TofPlay** [comment]
@armcast thanks 🙂
